// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  // Provide datasource URL here so schema can omit it; required for migrate/generate
  datasourceUrl: process.env["DATABASE_URL"],
  datasources: {
    db: {
      url: process.env["DATABASE_URL"],
    },
  },
});
